import type { Vendor } from "./types"

export const mockVendors: Vendor[] = [
  {
    id: "v1",
    name: "Elegant Seating Solutions",
    category: "Seating",
    description:
      "Premium seating arrangements for all types of events. We offer a wide range of chairs, tables, and lounge furniture to create the perfect atmosphere for your event.",
    priceRange: "$$$",
    rating: 4.8,
    reviewCount: 124,
    image: "/placeholder.svg?height=192&width=384&text=Elegant+Seating",
    location: {
      address: "123 Main St",
      city: "San Francisco",
      state: "CA",
      zip: "94105",
    },
    contact: {
      phone: "(415) 555-1234",
      email: "info@elegantseating.com",
      website: "www.elegantseating.com",
    },
    specialties: ["Wedding Seating", "Corporate Events", "Lounge Furniture", "Custom Arrangements"],
    isFavorite: true,
  },
  {
    id: "v2",
    name: "Brilliant Lights",
    category: "Lighting",
    description:
      "Transform your event space with our state-of-the-art lighting solutions. From ambient lighting to dramatic effects, we create the perfect mood for any occasion.",
    priceRange: "$$",
    rating: 4.5,
    reviewCount: 89,
    image: "/placeholder.svg?height=192&width=384&text=Brilliant+Lights",
    location: {
      address: "456 Market St",
      city: "San Francisco",
      state: "CA",
      zip: "94103",
    },
    contact: {
      phone: "(415) 555-5678",
      email: "info@brilliantlights.com",
      website: "www.brilliantlights.com",
    },
    specialties: ["Stage Lighting", "Ambient Effects", "LED Installations", "Outdoor Lighting"],
    isFavorite: false,
  },
  {
    id: "v3",
    name: "Harmony Music Productions",
    category: "Music",
    description:
      "Professional DJs and live musicians for all types of events. We customize our playlist and performance to match your event's theme and audience preferences.",
    priceRange: "$$$",
    rating: 4.9,
    reviewCount: 156,
    image: "/placeholder.svg?height=192&width=384&text=Harmony+Music",
    location: {
      address: "789 Howard St",
      city: "San Francisco",
      state: "CA",
      zip: "94107",
    },
    contact: {
      phone: "(415) 555-9012",
      email: "bookings@harmonymusic.com",
      website: "www.harmonymusic.com",
    },
    specialties: ["Wedding DJs", "Live Bands", "Corporate Events", "Custom Playlists"],
    isFavorite: true,
  },
  {
    id: "v4",
    name: "Gourmet Delights Catering",
    category: "Catering",
    description:
      "Exquisite catering services with a focus on locally-sourced ingredients and innovative cuisine. Our team of chefs creates memorable dining experiences for any event.",
    priceRange: "$$$$",
    rating: 4.7,
    reviewCount: 203,
    image: "/placeholder.svg?height=192&width=384&text=Gourmet+Delights",
    location: {
      address: "101 California St",
      city: "San Francisco",
      state: "CA",
      zip: "94111",
    },
    contact: {
      phone: "(415) 555-3456",
      email: "events@gourmetdelights.com",
      website: "www.gourmetdelights.com",
    },
    specialties: ["Fine Dining", "Cocktail Receptions", "Corporate Lunches", "Wedding Feasts"],
    isFavorite: false,
  },
  {
    id: "v5",
    name: "Floral Fantasy",
    category: "Florist",
    description:
      "Stunning floral arrangements that bring your event vision to life. From elegant centerpieces to elaborate installations, we create botanical magic for any occasion.",
    priceRange: "$$$",
    rating: 4.6,
    reviewCount: 118,
    image: "/placeholder.svg?height=192&width=384&text=Floral+Fantasy",
    location: {
      address: "222 Sutter St",
      city: "San Francisco",
      state: "CA",
      zip: "94108",
    },
    contact: {
      phone: "(415) 555-7890",
      email: "flowers@floralfantasy.com",
      website: "www.floralfantasy.com",
    },
    specialties: ["Wedding Bouquets", "Event Centerpieces", "Floral Installations", "Sustainable Arrangements"],
    isFavorite: false,
  },
  {
    id: "v6",
    name: "Grand Venues",
    category: "Venue",
    description:
      "Exceptional event spaces for gatherings of all sizes. Our portfolio includes historic buildings, modern lofts, and outdoor gardens to suit any event theme.",
    priceRange: "$$$$",
    rating: 4.8,
    reviewCount: 175,
    image: "/placeholder.svg?height=192&width=384&text=Grand+Venues",
    location: {
      address: "333 Post St",
      city: "San Francisco",
      state: "CA",
      zip: "94102",
    },
    contact: {
      phone: "(415) 555-2345",
      email: "bookings@grandvenues.com",
      website: "www.grandvenues.com",
    },
    specialties: ["Wedding Venues", "Corporate Spaces", "Outdoor Locations", "Historic Buildings"],
    isFavorite: true,
  },
  {
    id: "v7",
    name: "Capture Moments Photography",
    category: "Photography",
    description:
      "Award-winning photography services that document your event with style and creativity. Our photographers specialize in capturing authentic moments and emotions.",
    priceRange: "$$$",
    rating: 4.9,
    reviewCount: 142,
    image: "/placeholder.svg?height=192&width=384&text=Capture+Moments",
    location: {
      address: "444 Geary St",
      city: "New York",
      state: "NY",
      zip: "10001",
    },
    contact: {
      phone: "(212) 555-6789",
      email: "info@capturemoments.com",
      website: "www.capturemoments.com",
    },
    specialties: ["Wedding Photography", "Corporate Events", "Portrait Sessions", "Photo Booths"],
    isFavorite: false,
  },
  {
    id: "v8",
    name: "Decor Dreams",
    category: "Decor",
    description:
      "Transformative event decor that brings your vision to reality. From elegant weddings to themed corporate events, we design and install stunning decorative elements.",
    priceRange: "$$",
    rating: 4.5,
    reviewCount: 98,
    image: "/placeholder.svg?height=192&width=384&text=Decor+Dreams",
    location: {
      address: "555 Mission St",
      city: "Los Angeles",
      state: "CA",
      zip: "90012",
    },
    contact: {
      phone: "(213) 555-0123",
      email: "design@decordreams.com",
      website: "www.decordreams.com",
    },
    specialties: ["Theme Design", "Backdrop Installations", "Table Settings", "Balloon Decor"],
    isFavorite: false,
  },
  {
    id: "v9",
    name: "Elite Entertainment",
    category: "Entertainment",
    description:
      "Premium entertainment options for events of all types. From DJs and live bands to performers and interactive experiences, we keep your guests engaged and entertained.",
    priceRange: "$$$",
    rating: 4.7,
    reviewCount: 131,
    image: "/placeholder.svg?height=192&width=384&text=Elite+Entertainment",
    location: {
      address: "666 Folsom St",
      city: "Chicago",
      state: "IL",
      zip: "60601",
    },
    contact: {
      phone: "(312) 555-4567",
      email: "bookings@eliteentertainment.com",
      website: "www.eliteentertainment.com",
    },
    specialties: ["Live Performances", "Interactive Experiences", "Celebrity Impersonators", "Dance Shows"],
    isFavorite: true,
  },
  {
    id: "v10",
    name: "Swift Transportation",
    category: "Transportation",
    description:
      "Reliable and luxurious transportation services for event guests. Our fleet includes limousines, party buses, and executive sedans to ensure comfortable and stylish travel.",
    priceRange: "$$",
    rating: 4.4,
    reviewCount: 87,
    image: "/placeholder.svg?height=192&width=384&text=Swift+Transportation",
    location: {
      address: "777 Harrison St",
      city: "Boston",
      state: "MA",
      zip: "02110",
    },
    contact: {
      phone: "(617) 555-8901",
      email: "reservations@swifttransportation.com",
      website: "www.swifttransportation.com",
    },
    specialties: ["Wedding Transportation", "Corporate Shuttles", "VIP Services", "Airport Transfers"],
    isFavorite: false,
  },
  {
    id: "v11",
    name: "Sound Masters",
    category: "Music",
    description:
      "Professional sound and audio services for events of all sizes. Our state-of-the-art equipment and experienced technicians ensure perfect audio quality for speeches, music, and performances.",
    priceRange: "$$",
    rating: 4.6,
    reviewCount: 104,
    image: "/placeholder.svg?height=192&width=384&text=Sound+Masters",
    location: {
      address: "888 Brannan St",
      city: "Seattle",
      state: "WA",
      zip: "98101",
    },
    contact: {
      phone: "(206) 555-2345",
      email: "info@soundmasters.com",
      website: "www.soundmasters.com",
    },
    specialties: ["Live Sound Mixing", "Speaker Systems", "Microphone Setups", "Audio Recording"],
    isFavorite: false,
  },
  {
    id: "v12",
    name: "Comfort Seating Co.",
    category: "Seating",
    description:
      "Affordable and comfortable seating solutions for events of all types. We offer a variety of chairs, tables, and accessories to accommodate any number of guests in style.",
    priceRange: "$",
    rating: 4.3,
    reviewCount: 76,
    image: "/placeholder.svg?height=192&width=384&text=Comfort+Seating",
    location: {
      address: "999 Folsom St",
      city: "Denver",
      state: "CO",
      zip: "80202",
    },
    contact: {
      phone: "(303) 555-6789",
      email: "rentals@comfortseating.com",
      website: "www.comfortseating.com",
    },
    specialties: ["Chair Rentals", "Table Setups", "Outdoor Seating", "Budget-Friendly Options"],
    isFavorite: false,
  },
  {
    id: "v13",
    name: "Illumination Experts",
    category: "Lighting",
    description:
      "Specialized lighting design for events and productions. We create custom lighting plans that enhance your event's atmosphere and highlight key elements of your venue.",
    priceRange: "$$$",
    rating: 4.7,
    reviewCount: 112,
    image: "/placeholder.svg?height=192&width=384&text=Illumination+Experts",
    location: {
      address: "111 Pine St",
      city: "Miami",
      state: "FL",
      zip: "33130",
    },
    contact: {
      phone: "(305) 555-0123",
      email: "design@illuminationexperts.com",
      website: "www.illuminationexperts.com",
    },
    specialties: ["Architectural Lighting", "Event Spotlights", "Color Washes", "Dynamic Light Shows"],
    isFavorite: true,
  },
  {
    id: "v14",
    name: "Tasty Bites Catering",
    category: "Catering",
    description:
      "Delicious and affordable catering options for events of all sizes. Our diverse menu features international cuisines and accommodates various dietary preferences.",
    priceRange: "$$",
    rating: 4.5,
    reviewCount: 143,
    image: "/placeholder.svg?height=192&width=384&text=Tasty+Bites",
    location: {
      address: "222 Bush St",
      city: "Austin",
      state: "TX",
      zip: "78701",
    },
    contact: {
      phone: "(512) 555-4567",
      email: "orders@tastybites.com",
      website: "www.tastybites.com",
    },
    specialties: ["Buffet Service", "Passed Appetizers", "Food Stations", "Dietary Accommodations"],
    isFavorite: false,
  },
  {
    id: "v15",
    name: "Bloom & Blossom",
    category: "Florist",
    description:
      "Creative floral design for events and special occasions. Our talented florists work with seasonal blooms to create arrangements that complement your event's style and color palette.",
    priceRange: "$$",
    rating: 4.4,
    reviewCount: 91,
    image: "/placeholder.svg?height=192&width=384&text=Bloom+%26+Blossom",
    location: {
      address: "333 Market St",
      city: "Portland",
      state: "OR",
      zip: "97201",
    },
    contact: {
      phone: "(503) 555-8901",
      email: "flowers@bloomandblossom.com",
      website: "www.bloomandblossom.com",
    },
    specialties: ["Seasonal Arrangements", "Eco-Friendly Designs", "Budget Bouquets", "Plant Rentals"],
    isFavorite: false,
  },
]

